/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowRightIcon: typeof import('tdesign-icons-vue-next')['ArrowRightIcon']
    DeleteIcon: typeof import('tdesign-icons-vue-next')['DeleteIcon']
    Footer: typeof import('./src/components/Footer.vue')['default']
    JumpIcon: typeof import('tdesign-icons-vue-next')['JumpIcon']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/icon/Logo.vue')['default']
    LogoGithubFilledIcon: typeof import('tdesign-icons-vue-next')['LogoGithubFilledIcon']
    LogoQqFilledIcon: typeof import('tdesign-icons-vue-next')['LogoQqFilledIcon']
    MailIcon: typeof import('tdesign-icons-vue-next')['MailIcon']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlusIcon: typeof import('tdesign-icons-vue-next')['PlusIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TButton: typeof import('tdesign-vue-next')['Button']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UserAddIcon: typeof import('tdesign-icons-vue-next')['UserAddIcon']
    UsergroupAddIcon: typeof import('tdesign-icons-vue-next')['UsergroupAddIcon']
  }
}
